export const HOME_PAGE_PATH = 'Home'
export const PROFILE_PAGE_PATH = 'Profile'
export const MY_TASKS_PAGE_PATH = 'My Tasks'
export const NOTIFICATIONS_PAGE_PATH = 'Notifications'
export const WEBSITE_REDESIGN_PATH = 'WebsiteRedesign'
export const SETTINGS_PATH = 'Settings'

export const APP_PATH = 'App'
export const LOGIN_PATH = 'Login'
export const LOGOUT_PATH = 'Logout'
export const REGISTER_PATH = 'Register'

export const TASKS_PAGE_PATH = 'ProjectTasks'
export const BOARDS_PAGE_PATH = 'ProjectBoards'
export const ACTIVITY_PAGE_PATH = 'ProjectActivity'
export const CALENDAR_PAGE_PATH = 'ProjectCalendar'
